"""Self-check for the Heston calibration engine.

Validates:
  1. Recovery: calibrating to prices generated by a known Heston model returns
     parameters close to the generator (within loose tolerances — the Heston
     parameter space has mild identifiability limits).
  2. Fit quality: model prices reproduce the market prices to tight RMSE.
  3. Feller flag is set correctly for a Feller-satisfying generator.
  4. Input validation rejects empty/invalid contract lists.
"""

import math

import numpy as np

from app.engine.heston import HestonParams, price_european
from app.engine.heston_calibration import CalibrationContract, calibrate_heston


def _run_tests() -> None:
    # --- Market generation --------------------------------------------------
    true_params = HestonParams(v0=0.04, kappa=2.0, theta_v=0.04, sigma_v=0.3, rho=-0.7)
    S0, r, q = 100.0, 0.05, 0.01
    strikes = [80.0, 90.0, 95.0, 100.0, 105.0, 110.0, 120.0]
    ttms = [0.25, 0.5, 1.0]
    contracts: list[CalibrationContract] = []
    for ttm in ttms:
        for K in strikes:
            call = price_european(S0, K, ttm, r, q, true_params, "call")
            contracts.append(CalibrationContract(strike=K, ttm=ttm, market_price=call, option_type="call"))

    # --- 1. Parameter recovery ----------------------------------------------
    result = calibrate_heston(contracts, S0, r, q)
    p = result.params
    assert result.n_contracts == len(contracts)
    assert p.v0 > 0 and p.kappa > 0 and p.theta_v > 0 and p.sigma_v > 0 and -1 < p.rho < 1
    # Loose tolerances: prices, not params, are the objective.
    assert abs(p.v0 - true_params.v0) < 0.05, f"v0 off: {p.v0} vs {true_params.v0}"
    assert abs(p.kappa - true_params.kappa) < 1.5, f"kappa off: {p.kappa} vs {true_params.kappa}"
    assert abs(p.theta_v - true_params.theta_v) < 0.05, f"theta_v off: {p.theta_v} vs {true_params.theta_v}"
    assert abs(p.sigma_v - true_params.sigma_v) < 0.2, f"sigma_v off: {p.sigma_v} vs {true_params.sigma_v}"
    assert abs(p.rho - true_params.rho) < 0.2, f"rho off: {p.rho} vs {true_params.rho}"

    # --- 2. Fit quality -------------------------------------------------------
    assert result.rmse < 1e-3, f"Calibration RMSE too large: {result.rmse:.4e}"
    assert result.mape < 0.1, f"Calibration MAPE too large: {result.mape:.3f}%"
    assert result.max_abs_error < 1e-2, f"Max abs error too large: {result.max_abs_error:.4f}"

    # --- 3. Feller flag -------------------------------------------------------
    assert result.feller_condition_holds, "Generator satisfies Feller; flag should be True"

    # --- 4. Input validation --------------------------------------------------
    try:
        calibrate_heston([], S0, r, q)
        raise AssertionError("Expected ValueError for empty contracts")
    except ValueError:
        pass
    bad = [CalibrationContract(strike=100.0, ttm=0.5, market_price=-1.0, option_type="call")]
    try:
        calibrate_heston(bad, S0, r, q)
        raise AssertionError("Expected ValueError for non-positive market price")
    except ValueError:
        pass

    print("Heston calibration self-check OK")
    print(f"  fitted: v0={p.v0:.4f} kappa={p.kappa:.4f} theta_v={p.theta_v:.4f} "
          f"sigma_v={p.sigma_v:.4f} rho={p.rho:.4f}")
    print(f"  true:   v0={true_params.v0} kappa={true_params.kappa} theta_v={true_params.theta_v} "
          f"sigma_v={true_params.sigma_v} rho={true_params.rho}")
    print(f"  rmse={result.rmse:.2e} mape={result.mape:.3f}% max_abs={result.max_abs_error:.4f} "
          f"feller={result.feller_condition_holds}")


if __name__ == "__main__":
    _run_tests()
