"""Regenerate the frontend ticker database from Wikipedia constituent lists.

Fetches S&P 500 tickers from Wikipedia and Nifty 50 tickers from Wikipedia,
validates them with yfinance, and writes an updated ticker-data.ts file.

Usage:
    python scripts/update_tickers.py

Requires:
    pip install yfinance requests beautifulsoup4
"""

import json
import re
import sys
from pathlib import Path

import requests
import yfinance as yf

FRONTEND_DIR = Path(__file__).resolve().parent.parent / "frontend"
TICKER_FILE = FRONTEND_DIR / "lib" / "ticker-data.ts"

SP500_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
NIFTY50_URL = "https://en.wikipedia.org/wiki/NIFTY_50"


def fetch_sp500_tickers() -> list[tuple[str, str]]:
    """Fetch S&P 500 tickers and company names from Wikipedia."""
    resp = requests.get(SP500_URL, timeout=30)
    resp.raise_for_status()

    tickers: list[tuple[str, str]] = []
    pattern = re.compile(
        r"<tr><td>\d+</td><td>([A-Z]+)</td><td>(.*?)</td>"
    )
    for match in pattern.finditer(resp.text):
        ticker = match.group(1)
        name = match.group(2).strip()
        # Clean HTML entities
        name = name.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
        name = re.sub(r"<[^>]+>", "", name).strip()
        if ticker and name:
            tickers.append((ticker, name))

    return tickers


def fetch_nifty50_tickers() -> list[tuple[str, str]]:
    """Fetch Nifty 50 tickers and company names from Wikipedia."""
    resp = requests.get(NIFTY50_URL, timeout=30)
    resp.raise_for_status()

    tickers: list[tuple[str, str]] = []
    pattern = re.compile(
        r"<tr><td>\d+</td><td>([A-Z]+)</td><td>(.*?)</td>"
    )
    for match in pattern.finditer(resp.text):
        ticker = match.group(1)
        name = match.group(2).strip()
        name = name.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
        name = re.sub(r"<[^>]+>", "", name).strip()
        if ticker and name:
            tickers.append((ticker, name))

    return tickers


def validate_ticker(ticker: str, market: str) -> str | None:
    """Validate a ticker with yfinance and return the company name, or None."""
    symbol = ticker
    if market == "IN" and not ticker.endswith((".NS", ".BO")):
        symbol = f"{ticker}.NS"

    try:
        t = yf.Ticker(symbol)
        info = t.info or {}
        name = info.get("shortName") or info.get("longName") or ticker
        if name and name != "N/A":
            return name
    except Exception:
        pass
    return None


def generate_ticker_data(
    us_tickers: list[tuple[str, str]], in_tickers: list[tuple[str, str]]
) -> str:
    """Generate the ticker-data.ts file content."""
    lines = [
        '/**',
        ' * Shared Ticker Database & Autocomplete Utilities.',
        ' * Auto-generated by scripts/update_tickers.py.',
        ' */',
        '',
        'import { MarketRegion } from "./types";',
        '',
        'export interface TickerEntry {',
        '  ticker: string;',
        '  name: string;',
        '  market: MarketRegion;',
        '}',
        '',
        'export const TICKER_DATABASE: TickerEntry[] = [',
    ]

    for ticker, name in us_tickers:
        safe_name = name.replace('"', '\\"').replace("\n", " ").strip()
        lines.append(f'  {{ ticker: "{ticker}", name: "{safe_name}", market: "US" }},')

    lines.append("")

    for ticker, name in in_tickers:
        safe_name = name.replace('"', '\\"').replace("\n", " ").strip()
        lines.append(f'  {{ ticker: "{ticker}", name: "{safe_name}", market: "IN" }},')

    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    print("Fetching S&P 500 tickers...")
    sp500 = fetch_sp500_tickers()
    print(f"  Found {len(sp500)} S&P 500 tickers")

    print("Fetching Nifty 50 tickers...")
    nifty50 = fetch_nifty50_tickers()
    print(f"  Found {len(nifty50)} Nifty 50 tickers")

    print("Validating tickers with yfinance (this may take a few minutes)...")
    valid_us: list[tuple[str, str]] = []
    for i, (ticker, name) in enumerate(sp500):
        if i % 50 == 0 and i > 0:
            print(f"  Validated {i}/{len(sp500)} US tickers...")
        validated = validate_ticker(ticker, "US")
        if validated:
            valid_us.append((ticker, validated))

    valid_in: list[tuple[str, str]] = []
    for i, (ticker, name) in enumerate(nifty50):
        if i % 10 == 0 and i > 0:
            print(f"  Validated {i}/{len(nifty50)} IN tickers...")
        validated = validate_ticker(ticker, "IN")
        if validated:
            valid_in.append((ticker, validated))

    print(f"  Valid US: {len(valid_us)}/{len(sp500)}")
    print(f"  Valid IN: {len(valid_in)}/{len(nifty50)}")

    content = generate_ticker_data(valid_us, valid_in)

    backup_path = TICKER_FILE.with_suffix(".ts.bak")
    if TICKER_FILE.exists():
        TICKER_FILE.rename(backup_path)

    TICKER_FILE.write_text(content, encoding="utf-8")
    print(f"\nWrote {TICKER_FILE}")
    print(f"Backup saved to {backup_path}")

    if backup_path.exists():
        backup_path.unlink()


if __name__ == "__main__":
    main()