"""Smoke tests for the quant API endpoints.

These inject a fake market data service returning a synthetic options chain
generated by the Heston engine itself, so calibration/validation have a
ground-truth model to recover. Run: python -m app.api.test_quantitative
"""

from __future__ import annotations

import math
import sys
from datetime import date, timedelta

import numpy as np
from fastapi.testclient import TestClient

from ..engine.heston import HestonParams, price_european_many
from ..main import app
from ..providers.market_data import MarketDataService

S0 = 100.0
R = 0.05
Q = 0.0
TRUE_PARAMS = HestonParams(v0=0.04, kappa=2.0, theta_v=0.04, sigma_v=0.3, rho=-0.7)


def _synthetic_chain() -> dict:
    expiry = (date.today() + timedelta(days=30)).isoformat()
    T = 30 / 365.0
    forward = S0 * math.exp((R - Q) * T)
    strikes = [round(forward * math.exp(m), 2) for m in np.linspace(-0.4, 0.4, 15)]
    calls, puts = [], []
    call_prices = price_european_many(S0, np.asarray(strikes), T, R, Q, TRUE_PARAMS, "call")
    put_prices = price_european_many(S0, np.asarray(strikes), T, R, Q, TRUE_PARAMS, "put")
    for k, cp, pp in zip(strikes, call_prices, put_prices):
        calls.append({"strike": k, "bid": float(cp - 0.01), "ask": float(cp + 0.01),
                      "lastPrice": float(cp), "impliedVolatility": None, "volume": 100,
                      "openInterest": 500})
        puts.append({"strike": k, "bid": float(pp - 0.01), "ask": float(pp + 0.01),
                     "lastPrice": float(pp), "impliedVolatility": None, "volume": 100,
                     "openInterest": 500})
    return {
        "ticker": "SYNTH",
        "market": "US",
        "resolved_symbol": "SYNTH",
        "underlying_price": S0,
        "expiries": [expiry],
        "selected_expiry": expiry,
        "calls": calls,
        "puts": puts,
    }


class FakeMarketDataService(MarketDataService):
    def __init__(self) -> None:
        self._chain = _synthetic_chain()

    def get_options_chain(self, ticker: str, market: str, expiry: str | None = None) -> dict:
        chain = dict(self._chain)
        if expiry is not None:
            chain["selected_expiry"] = expiry
        return chain


def _client() -> TestClient:
    app.dependency_overrides.clear()
    from ..core.dependencies import get_market_data_service

    app.dependency_overrides[get_market_data_service] = lambda: FakeMarketDataService()
    return TestClient(app)


def test_vol_surface_smoke() -> None:
    with _client() as client:
        resp = client.post("/api/v1/quant/vol-surface", json={"ticker": "SYNTH"})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["spot"] == S0
    assert body["slices"], "expected at least one fitted slice"
    sl = body["slices"][0]
    assert abs(sl["ttm"] - 30 / 365.0) < 1e-3
    assert "svi_params" in sl
    ivs = [p["fitted_iv"] for p in sl["points"] if p["fitted_iv"] is not None]
    assert len(ivs) == len(sl["points"])
    assert all(iv > 0 for iv in ivs), "fitted IVs must be positive"


def test_heston_calibration_smoke() -> None:
    with _client() as client:
        resp = client.post("/api/v1/quant/heston-calibrate", json={"ticker": "SYNTH"})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    p = body["params"]
    # Should recover the true Heston params that generated the chain.
    assert abs(p["v0"] - TRUE_PARAMS.v0) < 0.02, p
    assert abs(p["theta_v"] - TRUE_PARAMS.theta_v) < 0.02, p
    assert abs(p["rho"] - TRUE_PARAMS.rho) < 0.15, p
    assert body["rmse"] < 1e-2, body["rmse"]
    assert body["contracts"], "expected per-contract views"
    assert abs(body["contracts"][0]["model_price"] - body["contracts"][0]["market_price"]) < 0.5


def test_model_validation_smoke() -> None:
    with _client() as client:
        resp = client.post("/api/v1/quant/model-validate", json={"ticker": "SYNTH"})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["price_rel_rmse"] < 1e-2, body["price_rel_rmse"]
    assert body["feller_condition_holds"] in (True, False)
    assert body["in_sample"] is True
    assert body["contracts"], "expected per-contract validation views"


if __name__ == "__main__":
    sys.path.insert(0, __file__)  # noqa
    test_vol_surface_smoke()
    print("vol-surface smoke OK")
    test_heston_calibration_smoke()
    print("heston-calibrate smoke OK")
    test_model_validation_smoke()
    print("model-validate smoke OK")
