/**
 * Shared Ticker Database & Autocomplete Utilities.
 */

import { MarketRegion } from "./types";

export interface TickerEntry {
  ticker: string;
  name: string;
  market: MarketRegion;
}

export const TICKER_DATABASE: TickerEntry[] = [
  { ticker: "MMM", name: "3M", market: "US" },
  { ticker: "AOS", name: "A. O. Smith", market: "US" },
  { ticker: "ABT", name: "Abbott Laboratories", market: "US" },
  { ticker: "ABBV", name: "AbbVie", market: "US" },
  { ticker: "ACN", name: "Accenture", market: "US" },
  { ticker: "ADBE", name: "Adobe Inc.", market: "US" },
  { ticker: "AMD", name: "Advanced Micro Devices", market: "US" },
  { ticker: "AES", name: "AES Corporation", market: "US" },
  { ticker: "AFL", name: "Aflac", market: "US" },
  { ticker: "A", name: "Agilent Technologies", market: "US" },
  { ticker: "APD", name: "Air Products", market: "US" },
  { ticker: "ABNB", name: "Airbnb", market: "US" },
  { ticker: "AKAM", name: "Akamai Technologies", market: "US" },
  { ticker: "ALB", name: "Albemarle Corporation", market: "US" },
  { ticker: "ARE", name: "Alexandria Real Estate Equities", market: "US" },
  { ticker: "ALGN", name: "Align Technology", market: "US" },
  { ticker: "ALLE", name: "Allegion", market: "US" },
  { ticker: "LNT", name: "Alliant Energy", market: "US" },
  { ticker: "ALL", name: "Allstate", market: "US" },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)", market: "US" },
  { ticker: "GOOG", name: "Alphabet Inc. (Class C)", market: "US" },
  { ticker: "MO", name: "Altria", market: "US" },
  { ticker: "AMZN", name: "Amazon", market: "US" },
  { ticker: "AMCR", name: "Amcor", market: "US" },
  { ticker: "AEE", name: "Ameren", market: "US" },
  { ticker: "AEP", name: "American Electric Power", market: "US" },
  { ticker: "AXP", name: "American Express", market: "US" },
  { ticker: "AIG", name: "American International Group", market: "US" },
  { ticker: "AMT", name: "American Tower", market: "US" },
  { ticker: "AWK", name: "American Water Works", market: "US" },
  { ticker: "AMP", name: "Ameriprise Financial", market: "US" },
  { ticker: "AME", name: "Ametek", market: "US" },
  { ticker: "AMGN", name: "Amgen", market: "US" },
  { ticker: "APH", name: "Amphenol", market: "US" },
  { ticker: "ADI", name: "Analog Devices", market: "US" },
  { ticker: "AON", name: "Aon plc", market: "US" },
  { ticker: "APA", name: "APA Corporation", market: "US" },
  { ticker: "APO", name: "Apollo Global Management", market: "US" },
  { ticker: "AAPL", name: "Apple Inc.", market: "US" },
  { ticker: "AMAT", name: "Applied Materials", market: "US" },
  { ticker: "APP", name: "AppLovin", market: "US" },
  { ticker: "APTV", name: "Aptiv", market: "US" },
  { ticker: "ACGL", name: "Arch Capital Group", market: "US" },
  { ticker: "ADM", name: "Archer Daniels Midland", market: "US" },
  { ticker: "ARES", name: "Ares Management", market: "US" },
  { ticker: "ANET", name: "Arista Networks", market: "US" },
  { ticker: "AJG", name: "Arthur J. Gallagher & Co.", market: "US" },
  { ticker: "AIZ", name: "Assurant", market: "US" },
  { ticker: "T", name: "AT&T", market: "US" },
  { ticker: "ATO", name: "Atmos Energy", market: "US" },
  { ticker: "ADSK", name: "Autodesk", market: "US" },
  { ticker: "ADP", name: "Automatic Data Processing", market: "US" },
  { ticker: "AZO", name: "AutoZone", market: "US" },
  { ticker: "AVB", name: "AvalonBay Communities", market: "US" },
  { ticker: "AVY", name: "Avery Dennison", market: "US" },
  { ticker: "AXON", name: "Axon Enterprise", market: "US" },
  { ticker: "BKR", name: "Baker Hughes", market: "US" },
  { ticker: "BALL", name: "Ball Corporation", market: "US" },
  { ticker: "BAC", name: "Bank of America", market: "US" },
  { ticker: "BAX", name: "Baxter International", market: "US" },
  { ticker: "BDX", name: "Becton Dickinson", market: "US" },
  { ticker: "BRK.B", name: "Berkshire Hathaway", market: "US" },
  { ticker: "BBY", name: "Best Buy", market: "US" },
  { ticker: "TECH", name: "Bio-Techne", market: "US" },
  { ticker: "BIIB", name: "Biogen", market: "US" },
  { ticker: "BLK", name: "BlackRock", market: "US" },
  { ticker: "BX", name: "Blackstone Inc.", market: "US" },
  { ticker: "XYZ", name: "Block, Inc.", market: "US" },
  { ticker: "BNY", name: "BNY Mellon", market: "US" },
  { ticker: "BA", name: "Boeing", market: "US" },
  { ticker: "BKNG", name: "Booking Holdings", market: "US" },
  { ticker: "BSX", name: "Boston Scientific", market: "US" },
  { ticker: "BMY", name: "Bristol Myers Squibb", market: "US" },
  { ticker: "AVGO", name: "Broadcom", market: "US" },
  { ticker: "BR", name: "Broadridge Financial Solutions", market: "US" },
  { ticker: "BRO", name: "Brown & Brown", market: "US" },
  { ticker: "BF.B", name: "Brown–Forman", market: "US" },
  { ticker: "BLDR", name: "Builders FirstSource", market: "US" },
  { ticker: "BG", name: "Bunge Global", market: "US" },
  { ticker: "BXP", name: "BXP, Inc.", market: "US" },
  { ticker: "CHRW", name: "C.H. Robinson", market: "US" },
  { ticker: "CDNS", name: "Cadence Design Systems", market: "US" },
  { ticker: "CPT", name: "Camden Property Trust", market: "US" },
  { ticker: "COF", name: "Capital One", market: "US" },
  { ticker: "CAH", name: "Cardinal Health", market: "US" },
  { ticker: "CCL", name: "Carnival Corporation", market: "US" },
  { ticker: "CARR", name: "Carrier Global", market: "US" },
  { ticker: "CVNA", name: "Carvana", market: "US" },
  { ticker: "CASY", name: "Casey's", market: "US" },
  { ticker: "CAT", name: "Caterpillar Inc.", market: "US" },
  { ticker: "CBOE", name: "Cboe Global Markets", market: "US" },
  { ticker: "CBRE", name: "CBRE Group", market: "US" },
  { ticker: "CDW", name: "CDW Corporation", market: "US" },
  { ticker: "COR", name: "Cencora", market: "US" },
  { ticker: "CNC", name: "Centene Corporation", market: "US" },
  { ticker: "CNP", name: "CenterPoint Energy", market: "US" },
  { ticker: "CF", name: "CF Industries", market: "US" },
  { ticker: "CRL", name: "Charles River Laboratories", market: "US" },
  { ticker: "SCHW", name: "Charles Schwab Corporation", market: "US" },
  { ticker: "CHTR", name: "Charter Communications", market: "US" },
  { ticker: "CVX", name: "Chevron Corporation", market: "US" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", market: "US" },
  { ticker: "CB", name: "Chubb Limited", market: "US" },
  { ticker: "CHD", name: "Church & Dwight", market: "US" },
  { ticker: "CIEN", name: "Ciena", market: "US" },
  { ticker: "CI", name: "Cigna", market: "US" },
  { ticker: "CINF", name: "Cincinnati Financial", market: "US" },
  { ticker: "CTAS", name: "Cintas", market: "US" },
  { ticker: "CSCO", name: "Cisco", market: "US" },
  { ticker: "C", name: "Citigroup", market: "US" },
  { ticker: "CFG", name: "Citizens Financial Group", market: "US" },
  { ticker: "CLX", name: "Clorox", market: "US" },
  { ticker: "CME", name: "CME Group", market: "US" },
  { ticker: "CMS", name: "CMS Energy", market: "US" },
  { ticker: "KO", name: "Coca-Cola Company (The)", market: "US" },
  { ticker: "CTSH", name: "Cognizant", market: "US" },
  { ticker: "COHR", name: "Coherent Corp.", market: "US" },
  { ticker: "COIN", name: "Coinbase", market: "US" },
  { ticker: "CL", name: "Colgate-Palmolive", market: "US" },
  { ticker: "CMCSA", name: "Comcast", market: "US" },
  { ticker: "FIX", name: "Comfort Systems USA", market: "US" },
  { ticker: "COP", name: "ConocoPhillips", market: "US" },
  { ticker: "ED", name: "Consolidated Edison", market: "US" },
  { ticker: "STZ", name: "Constellation Brands", market: "US" },
  { ticker: "CEG", name: "Constellation Energy", market: "US" },
  { ticker: "COO", name: "Cooper Companies (The)", market: "US" },
  { ticker: "CPRT", name: "Copart", market: "US" },
  { ticker: "GLW", name: "Corning Inc.", market: "US" },
  { ticker: "CPAY", name: "Corpay", market: "US" },
  { ticker: "CTVA", name: "Corteva", market: "US" },
  { ticker: "CSGP", name: "CoStar Group", market: "US" },
  { ticker: "COST", name: "Costco", market: "US" },
  { ticker: "CRH", name: "CRH plc", market: "US" },
  { ticker: "CRWD", name: "CrowdStrike", market: "US" },
  { ticker: "CCI", name: "Crown Castle", market: "US" },
  { ticker: "CSX", name: "CSX Corporation", market: "US" },
  { ticker: "CMI", name: "Cummins", market: "US" },
  { ticker: "CVS", name: "CVS Health", market: "US" },
  { ticker: "DHR", name: "Danaher Corporation", market: "US" },
  { ticker: "DRI", name: "Darden Restaurants", market: "US" },
  { ticker: "DDOG", name: "Datadog", market: "US" },
  { ticker: "DVA", name: "DaVita", market: "US" },
  { ticker: "DECK", name: "Deckers Brands", market: "US" },
  { ticker: "DE", name: "Deere & Company", market: "US" },
  { ticker: "DELL", name: "Dell Technologies", market: "US" },
  { ticker: "DAL", name: "Delta Air Lines", market: "US" },
  { ticker: "DVN", name: "Devon Energy", market: "US" },
  { ticker: "DXCM", name: "Dexcom", market: "US" },
  { ticker: "FANG", name: "Diamondback Energy", market: "US" },
  { ticker: "DLR", name: "Digital Realty", market: "US" },
  { ticker: "DG", name: "Dollar General", market: "US" },
  { ticker: "DLTR", name: "Dollar Tree", market: "US" },
  { ticker: "D", name: "Dominion Energy", market: "US" },
  { ticker: "DPZ", name: "Domino's", market: "US" },
  { ticker: "DASH", name: "DoorDash", market: "US" },
  { ticker: "DOV", name: "Dover Corporation", market: "US" },
  { ticker: "DOW", name: "Dow Inc.", market: "US" },
  { ticker: "DHI", name: "D. R. Horton", market: "US" },
  { ticker: "DTE", name: "DTE Energy", market: "US" },
  { ticker: "DUK", name: "Duke Energy", market: "US" },
  { ticker: "DD", name: "DuPont", market: "US" },
  { ticker: "ETN", name: "Eaton Corporation", market: "US" },
  { ticker: "EBAY", name: "eBay Inc.", market: "US" },
  { ticker: "ECHO", name: "EchoStar", market: "US" },
  { ticker: "ECL", name: "Ecolab", market: "US" },
  { ticker: "EIX", name: "Edison International", market: "US" },
  { ticker: "EW", name: "Edwards Lifesciences", market: "US" },
  { ticker: "EA", name: "Electronic Arts", market: "US" },
  { ticker: "ELV", name: "Elevance Health", market: "US" },
  { ticker: "EME", name: "Emcor", market: "US" },
  { ticker: "EMR", name: "Emerson Electric", market: "US" },
  { ticker: "ETR", name: "Entergy", market: "US" },
  { ticker: "EOG", name: "EOG Resources", market: "US" },
  { ticker: "EQT", name: "EQT Corporation", market: "US" },
  { ticker: "EFX", name: "Equifax", market: "US" },
  { ticker: "EQIX", name: "Equinix", market: "US" },
  { ticker: "EQR", name: "Equity Residential", market: "US" },
  { ticker: "ERIE", name: "Erie Indemnity", market: "US" },
  { ticker: "ESS", name: "Essex Property Trust", market: "US" },
  { ticker: "EL", name: "Estée Lauder Companies (The)", market: "US" },
  { ticker: "EG", name: "Everest Group", market: "US" },
  { ticker: "EVRG", name: "Evergy", market: "US" },
  { ticker: "ES", name: "Eversource Energy", market: "US" },
  { ticker: "EXC", name: "Exelon", market: "US" },
  { ticker: "EXE", name: "Expand Energy", market: "US" },
  { ticker: "EXPE", name: "Expedia Group", market: "US" },
  { ticker: "EXPD", name: "Expeditors International", market: "US" },
  { ticker: "EXR", name: "Extra Space Storage", market: "US" },
  { ticker: "XOM", name: "ExxonMobil", market: "US" },
  { ticker: "FFIV", name: "F5, Inc.", market: "US" },
  { ticker: "FDS", name: "FactSet", market: "US" },
  { ticker: "FICO", name: "Fair Isaac", market: "US" },
  { ticker: "FAST", name: "Fastenal", market: "US" },
  { ticker: "FRT", name: "Federal Realty Investment Trust", market: "US" },
  { ticker: "FDX", name: "FedEx", market: "US" },
  { ticker: "FDXF", name: "FedEx Freight", market: "US" },
  { ticker: "FIS", name: "Fidelity National Information Services", market: "US" },
  { ticker: "FITB", name: "Fifth Third Bancorp", market: "US" },
  { ticker: "FSLR", name: "First Solar", market: "US" },
  { ticker: "FE", name: "FirstEnergy", market: "US" },
  { ticker: "FISV", name: "Fiserv", market: "US" },
  { ticker: "FLEX", name: "Flex Ltd.", market: "US" },
  { ticker: "F", name: "Ford Motor Company", market: "US" },
  { ticker: "FTNT", name: "Fortinet", market: "US" },
  { ticker: "FTV", name: "Fortive", market: "US" },
  { ticker: "FOXA", name: "Fox Corporation (Class A)", market: "US" },
  { ticker: "FOX", name: "Fox Corporation (Class B)", market: "US" },
  { ticker: "BEN", name: "Franklin Resources", market: "US" },
  { ticker: "FCX", name: "Freeport-McMoRan", market: "US" },
  { ticker: "GRMN", name: "Garmin", market: "US" },
  { ticker: "IT", name: "Gartner", market: "US" },
  { ticker: "GE", name: "GE Aerospace", market: "US" },
  { ticker: "GEHC", name: "GE HealthCare", market: "US" },
  { ticker: "GEV", name: "GE Vernova", market: "US" },
  { ticker: "GEN", name: "Gen Digital", market: "US" },
  { ticker: "GNRC", name: "Generac", market: "US" },
  { ticker: "GD", name: "General Dynamics", market: "US" },
  { ticker: "GIS", name: "General Mills", market: "US" },
  { ticker: "GM", name: "General Motors", market: "US" },
  { ticker: "GPC", name: "Genuine Parts Company", market: "US" },
  { ticker: "GILD", name: "Gilead Sciences", market: "US" },
  { ticker: "GPN", name: "Global Payments", market: "US" },
  { ticker: "GL", name: "Globe Life", market: "US" },
  { ticker: "GDDY", name: "GoDaddy", market: "US" },
  { ticker: "GS", name: "Goldman Sachs", market: "US" },
  { ticker: "HAL", name: "Halliburton", market: "US" },
  { ticker: "HIG", name: "Hartford (The)", market: "US" },
  { ticker: "HAS", name: "Hasbro", market: "US" },
  { ticker: "HCA", name: "HCA Healthcare", market: "US" },
  { ticker: "DOC", name: "Healthpeak Properties", market: "US" },
  { ticker: "HSIC", name: "Henry Schein", market: "US" },
  { ticker: "HSY", name: "Hershey Company (The)", market: "US" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", market: "US" },
  { ticker: "HLT", name: "Hilton Worldwide", market: "US" },
  { ticker: "HD", name: "Home Depot (The)", market: "US" },
  { ticker: "HONA", name: "Honeywell Aerospace", market: "US" },
  { ticker: "HON", name: "Honeywell Technologies", market: "US" },
  { ticker: "HRL", name: "Hormel Foods", market: "US" },
  { ticker: "HST", name: "Host Hotels & Resorts", market: "US" },
  { ticker: "HWM", name: "Howmet Aerospace", market: "US" },
  { ticker: "HPQ", name: "HP Inc.", market: "US" },
  { ticker: "HUBB", name: "Hubbell Incorporated", market: "US" },
  { ticker: "HUM", name: "Humana", market: "US" },
  { ticker: "HBAN", name: "Huntington Bancshares", market: "US" },
  { ticker: "HII", name: "Huntington Ingalls Industries", market: "US" },
  { ticker: "IBM", name: "IBM", market: "US" },
  { ticker: "IEX", name: "IDEX Corporation", market: "US" },
  { ticker: "IDXX", name: "Idexx Laboratories", market: "US" },
  { ticker: "ITW", name: "Illinois Tool Works", market: "US" },
  { ticker: "INCY", name: "Incyte", market: "US" },
  { ticker: "IR", name: "Ingersoll Rand", market: "US" },
  { ticker: "PODD", name: "Insulet Corporation", market: "US" },
  { ticker: "INTC", name: "Intel", market: "US" },
  { ticker: "IBKR", name: "Interactive Brokers", market: "US" },
  { ticker: "ICE", name: "Intercontinental Exchange", market: "US" },
  { ticker: "IFF", name: "International Flavors & Fragrances", market: "US" },
  { ticker: "IP", name: "International Paper", market: "US" },
  { ticker: "INTU", name: "Intuit", market: "US" },
  { ticker: "ISRG", name: "Intuitive Surgical", market: "US" },
  { ticker: "IVZ", name: "Invesco", market: "US" },
  { ticker: "INVH", name: "Invitation Homes", market: "US" },
  { ticker: "IQV", name: "IQVIA", market: "US" },
  { ticker: "IRM", name: "Iron Mountain", market: "US" },
  { ticker: "JBHT", name: "J.B. Hunt", market: "US" },
  { ticker: "JBL", name: "Jabil", market: "US" },
  { ticker: "JKHY", name: "Jack Henry & Associates", market: "US" },
  { ticker: "J", name: "Jacobs Solutions", market: "US" },
  { ticker: "JNJ", name: "Johnson & Johnson", market: "US" },
  { ticker: "JCI", name: "Johnson Controls", market: "US" },
  { ticker: "JPM", name: "JPMorgan Chase", market: "US" },
  { ticker: "KVUE", name: "Kenvue", market: "US" },
  { ticker: "KDP", name: "Keurig Dr Pepper", market: "US" },
  { ticker: "KEY", name: "KeyCorp", market: "US" },
  { ticker: "KEYS", name: "Keysight Technologies", market: "US" },
  { ticker: "KMB", name: "Kimberly-Clark", market: "US" },
  { ticker: "KIM", name: "Kimco Realty", market: "US" },
  { ticker: "KMI", name: "Kinder Morgan", market: "US" },
  { ticker: "KKR", name: "KKR & Co.", market: "US" },
  { ticker: "KLAC", name: "KLA Corporation", market: "US" },
  { ticker: "KHC", name: "Kraft Heinz", market: "US" },
  { ticker: "KR", name: "Kroger", market: "US" },
  { ticker: "LHX", name: "L3Harris", market: "US" },
  { ticker: "LH", name: "Labcorp", market: "US" },
  { ticker: "LRCX", name: "Lam Research", market: "US" },
  { ticker: "LVS", name: "Las Vegas Sands", market: "US" },
  { ticker: "LDOS", name: "Leidos", market: "US" },
  { ticker: "LEN", name: "Lennar", market: "US" },
  { ticker: "LII", name: "Lennox International", market: "US" },
  { ticker: "LLY", name: "Lilly (Eli)", market: "US" },
  { ticker: "LIN", name: "Linde plc", market: "US" },
  { ticker: "LYV", name: "Live Nation Entertainment", market: "US" },
  { ticker: "LMT", name: "Lockheed Martin", market: "US" },
  { ticker: "L", name: "Loews Corporation", market: "US" },
  { ticker: "LOW", name: "Lowe's", market: "US" },
  { ticker: "LULU", name: "Lululemon Athletica", market: "US" },
  { ticker: "LITE", name: "Lumentum", market: "US" },
  { ticker: "LYB", name: "LyondellBasell", market: "US" },
  { ticker: "MTB", name: "M&T Bank", market: "US" },
  { ticker: "MPC", name: "Marathon Petroleum", market: "US" },
  { ticker: "MAR", name: "Marriott International", market: "US" },
  { ticker: "MRSH", name: "Marsh McLennan", market: "US" },
  { ticker: "MLM", name: "Martin Marietta Materials", market: "US" },
  { ticker: "MRVL", name: "Marvell Technology", market: "US" },
  { ticker: "MAS", name: "Masco", market: "US" },
  { ticker: "MA", name: "Mastercard", market: "US" },
  { ticker: "MKC", name: "McCormick & Company", market: "US" },
  { ticker: "MCD", name: "McDonald's", market: "US" },
  { ticker: "MCK", name: "McKesson Corporation", market: "US" },
  { ticker: "MDT", name: "Medtronic", market: "US" },
  { ticker: "MRK", name: "Merck & Co.", market: "US" },
  { ticker: "META", name: "Meta Platforms", market: "US" },
  { ticker: "MET", name: "MetLife", market: "US" },
  { ticker: "MTD", name: "Mettler Toledo", market: "US" },
  { ticker: "MGM", name: "MGM Resorts", market: "US" },
  { ticker: "MCHP", name: "Microchip Technology", market: "US" },
  { ticker: "MU", name: "Micron Technology", market: "US" },
  { ticker: "MSFT", name: "Microsoft", market: "US" },
  { ticker: "MAA", name: "Mid-America Apartment Communities", market: "US" },
  { ticker: "MRNA", name: "Moderna", market: "US" },
  { ticker: "TAP", name: "Molson Coors Beverage Company", market: "US" },
  { ticker: "MDLZ", name: "Mondelez International", market: "US" },
  { ticker: "MPWR", name: "Monolithic Power Systems", market: "US" },
  { ticker: "MNST", name: "Monster Beverage", market: "US" },
  { ticker: "MCO", name: "Moody's Corporation", market: "US" },
  { ticker: "MS", name: "Morgan Stanley", market: "US" },
  { ticker: "MOS", name: "Mosaic Company (The)", market: "US" },
  { ticker: "MSI", name: "Motorola Solutions", market: "US" },
  { ticker: "MSCI", name: "MSCI Inc.", market: "US" },
  { ticker: "NDAQ", name: "Nasdaq, Inc.", market: "US" },
  { ticker: "NTAP", name: "NetApp", market: "US" },
  { ticker: "NFLX", name: "Netflix", market: "US" },
  { ticker: "NEM", name: "Newmont", market: "US" },
  { ticker: "NWSA", name: "News Corp (Class A)", market: "US" },
  { ticker: "NWS", name: "News Corp (Class B)", market: "US" },
  { ticker: "NEE", name: "NextEra Energy", market: "US" },
  { ticker: "NKE", name: "Nike, Inc.", market: "US" },
  { ticker: "NI", name: "NiSource", market: "US" },
  { ticker: "NDSN", name: "Nordson Corporation", market: "US" },
  { ticker: "NSC", name: "Norfolk Southern", market: "US" },
  { ticker: "NTRS", name: "Northern Trust", market: "US" },
  { ticker: "NOC", name: "Northrop Grumman", market: "US" },
  { ticker: "NCLH", name: "Norwegian Cruise Line Holdings", market: "US" },
  { ticker: "NRG", name: "NRG Energy", market: "US" },
  { ticker: "NUE", name: "Nucor", market: "US" },
  { ticker: "NVDA", name: "Nvidia", market: "US" },
  { ticker: "NVR", name: "NVR, Inc.", market: "US" },
  { ticker: "NXPI", name: "NXP Semiconductors", market: "US" },
  { ticker: "ORLY", name: "O’Reilly Automotive", market: "US" },
  { ticker: "OXY", name: "Occidental Petroleum", market: "US" },
  { ticker: "ODFL", name: "Old Dominion", market: "US" },
  { ticker: "OMC", name: "Omnicom Group", market: "US" },
  { ticker: "ON", name: "ON Semiconductor", market: "US" },
  { ticker: "OKE", name: "Oneok", market: "US" },
  { ticker: "ORCL", name: "Oracle Corporation", market: "US" },
  { ticker: "OTIS", name: "Otis Worldwide", market: "US" },
  { ticker: "PCAR", name: "Paccar", market: "US" },
  { ticker: "PKG", name: "Packaging Corporation of America", market: "US" },
  { ticker: "PLTR", name: "Palantir Technologies", market: "US" },
  { ticker: "PANW", name: "Palo Alto Networks", market: "US" },
  { ticker: "PSKY", name: "Paramount Skydance Corporation", market: "US" },
  { ticker: "PH", name: "Parker Hannifin", market: "US" },
  { ticker: "PAYX", name: "Paychex", market: "US" },
  { ticker: "PYPL", name: "PayPal", market: "US" },
  { ticker: "PNR", name: "Pentair", market: "US" },
  { ticker: "PEP", name: "PepsiCo", market: "US" },
  { ticker: "PFE", name: "Pfizer", market: "US" },
  { ticker: "PCG", name: "PG&E Corporation", market: "US" },
  { ticker: "PM", name: "Philip Morris International", market: "US" },
  { ticker: "PSX", name: "Phillips 66", market: "US" },
  { ticker: "PNW", name: "Pinnacle West Capital", market: "US" },
  { ticker: "PNC", name: "PNC Financial Services", market: "US" },
  { ticker: "PPG", name: "PPG Industries", market: "US" },
  { ticker: "PPL", name: "PPL Corporation", market: "US" },
  { ticker: "PFG", name: "Principal Financial Group", market: "US" },
  { ticker: "PG", name: "Procter & Gamble", market: "US" },
  { ticker: "PGR", name: "Progressive Corporation", market: "US" },
  { ticker: "PLD", name: "Prologis", market: "US" },
  { ticker: "PRU", name: "Prudential Financial", market: "US" },
  { ticker: "PEG", name: "Public Service Enterprise Group", market: "US" },
  { ticker: "PTC", name: "PTC Inc.", market: "US" },
  { ticker: "PSA", name: "Public Storage", market: "US" },
  { ticker: "PHM", name: "PulteGroup", market: "US" },
  { ticker: "PWR", name: "Quanta Services", market: "US" },
  { ticker: "QCOM", name: "Qualcomm", market: "US" },
  { ticker: "DGX", name: "Quest Diagnostics", market: "US" },
  { ticker: "Q", name: "Qnity Electronics", market: "US" },
  { ticker: "RL", name: "Ralph Lauren Corporation", market: "US" },
  { ticker: "RJF", name: "Raymond James Financial", market: "US" },
  { ticker: "RTX", name: "RTX Corporation", market: "US" },
  { ticker: "O", name: "Realty Income", market: "US" },
  { ticker: "REG", name: "Regency Centers", market: "US" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", market: "US" },
  { ticker: "RF", name: "Regions Financial Corporation", market: "US" },
  { ticker: "RSG", name: "Republic Services", market: "US" },
  { ticker: "RMD", name: "ResMed", market: "US" },
  { ticker: "RVTY", name: "Revvity", market: "US" },
  { ticker: "HOOD", name: "Robinhood Markets", market: "US" },
  { ticker: "ROK", name: "Rockwell Automation", market: "US" },
  { ticker: "ROL", name: "Rollins, Inc.", market: "US" },
  { ticker: "ROP", name: "Roper Technologies", market: "US" },
  { ticker: "ROST", name: "Ross Stores", market: "US" },
  { ticker: "RCL", name: "Royal Caribbean Group", market: "US" },
  { ticker: "SPGI", name: "S&P Global", market: "US" },
  { ticker: "CRM", name: "Salesforce", market: "US" },
  { ticker: "SNDK", name: "Sandisk", market: "US" },
  { ticker: "SBAC", name: "SBA Communications", market: "US" },
  { ticker: "SLB", name: "Schlumberger", market: "US" },
  { ticker: "STX", name: "Seagate Technology", market: "US" },
  { ticker: "SRE", name: "Sempra", market: "US" },
  { ticker: "NOW", name: "ServiceNow", market: "US" },
  { ticker: "SHW", name: "Sherwin-Williams", market: "US" },
  { ticker: "SPG", name: "Simon Property Group", market: "US" },
  { ticker: "SWKS", name: "Skyworks Solutions", market: "US" },
  { ticker: "SJM", name: "J.M. Smucker Company (The)", market: "US" },
  { ticker: "SW", name: "Smurfit Westrock", market: "US" },
  { ticker: "SNA", name: "Snap-on", market: "US" },
  { ticker: "SOLV", name: "Solventum", market: "US" },
  { ticker: "SO", name: "Southern Company", market: "US" },
  { ticker: "LUV", name: "Southwest Airlines", market: "US" },
  { ticker: "SWK", name: "Stanley Black & Decker", market: "US" },
  { ticker: "SBUX", name: "Starbucks", market: "US" },
  { ticker: "STT", name: "State Street Corporation", market: "US" },
  { ticker: "STLD", name: "Steel Dynamics", market: "US" },
  { ticker: "STE", name: "Steris", market: "US" },
  { ticker: "SYK", name: "Stryker Corporation", market: "US" },
  { ticker: "SMCI", name: "Supermicro", market: "US" },
  { ticker: "SYF", name: "Synchrony Financial", market: "US" },
  { ticker: "SNPS", name: "Synopsys", market: "US" },
  { ticker: "SYY", name: "Sysco", market: "US" },
  { ticker: "TMUS", name: "T-Mobile US", market: "US" },
  { ticker: "TROW", name: "T. Rowe Price", market: "US" },
  { ticker: "TTWO", name: "Take-Two Interactive", market: "US" },
  { ticker: "TPR", name: "Tapestry, Inc.", market: "US" },
  { ticker: "TRGP", name: "Targa Resources", market: "US" },
  { ticker: "TGT", name: "Target Corporation", market: "US" },
  { ticker: "TEL", name: "TE Connectivity", market: "US" },
  { ticker: "TDY", name: "Teledyne Technologies", market: "US" },
  { ticker: "TER", name: "Teradyne", market: "US" },
  { ticker: "TSLA", name: "Tesla, Inc.", market: "US" },
  { ticker: "TXN", name: "Texas Instruments", market: "US" },
  { ticker: "TPL", name: "Texas Pacific Land Corporation", market: "US" },
  { ticker: "TXT", name: "Textron", market: "US" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", market: "US" },
  { ticker: "TJX", name: "TJX Companies", market: "US" },
  { ticker: "TKO", name: "TKO Group Holdings", market: "US" },
  { ticker: "TTD", name: "Trade Desk (The)", market: "US" },
  { ticker: "TSCO", name: "Tractor Supply", market: "US" },
  { ticker: "TT", name: "Trane Technologies", market: "US" },
  { ticker: "TDG", name: "TransDigm Group", market: "US" },
  { ticker: "TRV", name: "Travelers Companies (The)", market: "US" },
  { ticker: "TRMB", name: "Trimble Inc.", market: "US" },
  { ticker: "TFC", name: "Truist Financial", market: "US" },
  { ticker: "TYL", name: "Tyler Technologies", market: "US" },
  { ticker: "TSN", name: "Tyson Foods", market: "US" },
  { ticker: "USB", name: "U.S. Bancorp", market: "US" },
  { ticker: "UBER", name: "Uber", market: "US" },
  { ticker: "UDR", name: "UDR, Inc.", market: "US" },
  { ticker: "ULTA", name: "Ulta Beauty", market: "US" },
  { ticker: "UNP", name: "Union Pacific Corporation", market: "US" },
  { ticker: "UAL", name: "United Airlines Holdings", market: "US" },
  { ticker: "UPS", name: "United Parcel Service", market: "US" },
  { ticker: "URI", name: "United Rentals", market: "US" },
  { ticker: "UNH", name: "UnitedHealth Group", market: "US" },
  { ticker: "UHS", name: "Universal Health Services", market: "US" },
  { ticker: "VLO", name: "Valero Energy", market: "US" },
  { ticker: "VEEV", name: "Veeva Systems", market: "US" },
  { ticker: "VTR", name: "Ventas", market: "US" },
  { ticker: "VLTO", name: "Veralto", market: "US" },
  { ticker: "VRSN", name: "Verisign", market: "US" },
  { ticker: "VRSK", name: "Verisk Analytics", market: "US" },
  { ticker: "VZ", name: "Verizon", market: "US" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", market: "US" },
  { ticker: "VRT", name: "Vertiv", market: "US" },
  { ticker: "VTRS", name: "Viatris", market: "US" },
  { ticker: "VICI", name: "Vici Properties", market: "US" },
  { ticker: "V", name: "Visa Inc.", market: "US" },
  { ticker: "VST", name: "Vistra Corp .", market: "US" },
  { ticker: "VMC", name: "Vulcan Materials Company", market: "US" },
  { ticker: "WRB", name: "W. R. Berkley Corporation", market: "US" },
  { ticker: "GWW", name: "W. W. Grainger", market: "US" },
  { ticker: "WAB", name: "Wabtec", market: "US" },
  { ticker: "WMT", name: "Walmart", market: "US" },
  { ticker: "DIS", name: "Walt Disney Company (The)", market: "US" },
  { ticker: "WBD", name: "Warner Bros. Discovery", market: "US" },
  { ticker: "WM", name: "Waste Management", market: "US" },
  { ticker: "WAT", name: "Waters Corporation", market: "US" },
  { ticker: "WEC", name: "WEC Energy Group", market: "US" },
  { ticker: "WFC", name: "Wells Fargo", market: "US" },
  { ticker: "WELL", name: "Welltower", market: "US" },
  { ticker: "WST", name: "West Pharmaceutical Services", market: "US" },
  { ticker: "WDC", name: "Western Digital", market: "US" },
  { ticker: "WY", name: "Weyerhaeuser", market: "US" },
  { ticker: "WSM", name: "Williams-Sonoma, Inc.", market: "US" },
  { ticker: "WMB", name: "Williams Companies", market: "US" },
  { ticker: "WTW", name: "Willis Towers Watson", market: "US" },
  { ticker: "WDAY", name: "Workday, Inc.", market: "US" },
  { ticker: "WYNN", name: "Wynn Resorts", market: "US" },
  { ticker: "XEL", name: "Xcel Energy", market: "US" },
  { ticker: "XYL", name: "Xylem Inc.", market: "US" },
  { ticker: "YUM", name: "Yum! Brands", market: "US" },
  { ticker: "ZBRA", name: "Zebra Technologies", market: "US" },
  { ticker: "ZBH", name: "Zimmer Biomet", market: "US" },
  { ticker: "ZTS", name: "Zoetis", market: "US" },

  { ticker: "ADANIENT", name: "Adani Enterprises", market: "IN" },
  { ticker: "ADANIPORTS", name: "Adani Ports & SEZ", market: "IN" },
  { ticker: "APOLLOHOSP", name: "Apollo Hospitals", market: "IN" },
  { ticker: "ASIANPAINT", name: "Asian Paints", market: "IN" },
  { ticker: "AXISBANK", name: "Axis Bank", market: "IN" },
  { ticker: "BAJFINANCE", name: "Bajaj Finance", market: "IN" },
  { ticker: "BAJAJFINSV", name: "Bajaj Finserv", market: "IN" },
  { ticker: "BEL", name: "Bharat Electronics", market: "IN" },
  { ticker: "BHARTIARTL", name: "Bharti Airtel", market: "IN" },
  { ticker: "CIPLA", name: "Cipla", market: "IN" },
  { ticker: "COALINDIA", name: "Coal India", market: "IN" },
  { ticker: "DRREDDY", name: "Dr. Reddy's Laboratories", market: "IN" },
  { ticker: "EICHERMOT", name: "Eicher Motors", market: "IN" },
  { ticker: "ETERNAL", name: "Eternal", market: "IN" },
  { ticker: "GRASIM", name: "Grasim Industries", market: "IN" },
  { ticker: "HCLTECH", name: "HCLTech", market: "IN" },
  { ticker: "HDFCBANK", name: "HDFC Bank", market: "IN" },
  { ticker: "HDFCLIFE", name: "HDFC Life", market: "IN" },
  { ticker: "HINDALCO", name: "Hindalco Industries", market: "IN" },
  { ticker: "HINDUNILVR", name: "Hindustan Unilever", market: "IN" },
  { ticker: "ICICIBANK", name: "ICICI Bank", market: "IN" },
  { ticker: "INDIGO", name: "IndiGo", market: "IN" },
  { ticker: "INFY", name: "Infosys", market: "IN" },
  { ticker: "ITC", name: "ITC", market: "IN" },
  { ticker: "JIOFIN", name: "Jio Financial Services", market: "IN" },
  { ticker: "JSWSTEEL", name: "JSW Steel", market: "IN" },
  { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank", market: "IN" },
  { ticker: "LT", name: "Larsen & Toubro", market: "IN" },
  { ticker: "MARUTI", name: "Maruti Suzuki", market: "IN" },
  { ticker: "MAXHEALTH", name: "Max Healthcare", market: "IN" },
  { ticker: "NESTLEIND", name: "Nestlé India", market: "IN" },
  { ticker: "NTPC", name: "NTPC", market: "IN" },
  { ticker: "ONGC", name: "Oil and Natural Gas Corporation", market: "IN" },
  { ticker: "POWERGRID", name: "Power Grid", market: "IN" },
  { ticker: "RELIANCE", name: "Reliance Industries", market: "IN" },
  { ticker: "SBILIFE", name: "SBI Life Insurance Company", market: "IN" },
  { ticker: "SHRIRAMFIN", name: "Shriram Finance", market: "IN" },
  { ticker: "SBIN", name: "State Bank of India", market: "IN" },
  { ticker: "SUNPHARMA", name: "Sun Pharma", market: "IN" },
  { ticker: "TCS", name: "Tata Consultancy Services", market: "IN" },
  { ticker: "TATACONSUM", name: "Tata Consumer Products", market: "IN" },
  { ticker: "TMPV", name: "Tata Motors Passenger Vehicles", market: "IN" },
  { ticker: "TATASTEEL", name: "Tata Steel", market: "IN" },
  { ticker: "TECHM", name: "Tech Mahindra", market: "IN" },
  { ticker: "TITAN", name: "Titan Company", market: "IN" },
  { ticker: "TRENT", name: "Trent", market: "IN" },
  { ticker: "ULTRACEMCO", name: "UltraTech Cement", market: "IN" },
  { ticker: "WIPRO", name: "Wipro", market: "IN" },

  { ticker: "EURUSD", name: "EUR/USD", market: "FX" },
  { ticker: "GBPUSD", name: "GBP/USD", market: "FX" },
  { ticker: "USDJPY", name: "USD/JPY", market: "FX" },
  { ticker: "USDCHF", name: "USD/CHF", market: "FX" },
  { ticker: "AUDUSD", name: "AUD/USD", market: "FX" },
  { ticker: "USDCAD", name: "USD/CAD", market: "FX" },
  { ticker: "NZDUSD", name: "NZD/USD", market: "FX" },
  { ticker: "EURGBP", name: "EUR/GBP", market: "FX" },
  { ticker: "EURJPY", name: "EUR/JPY", market: "FX" },
  { ticker: "GBPJPY", name: "GBP/JPY", market: "FX" },
  { ticker: "AUDJPY", name: "AUD/JPY", market: "FX" },
  { ticker: "EURAUD", name: "EUR/AUD", market: "FX" },
  { ticker: "EURCHF", name: "EUR/CHF", market: "FX" },
  { ticker: "USDINR", name: "USD/INR", market: "FX" },
  { ticker: "BTC", name: "Bitcoin", market: "CRYPTO" },
  { ticker: "ETH", name: "Ethereum", market: "CRYPTO" },
  { ticker: "SOL", name: "Solana", market: "CRYPTO" },
  { ticker: "BNB", name: "Binance Coin", market: "CRYPTO" },
  { ticker: "XRP", name: "Ripple", market: "CRYPTO" },
  { ticker: "ADA", name: "Cardano", market: "CRYPTO" },
  { ticker: "DOGE", name: "Dogecoin", market: "CRYPTO" },
  { ticker: "AVAX", name: "Avalanche", market: "CRYPTO" },
  { ticker: "DOT", name: "Polkadot", market: "CRYPTO" },
  { ticker: "MATIC", name: "Polygon", market: "CRYPTO" },
  { ticker: "LINK", name: "Chainlink", market: "CRYPTO" },
  { ticker: "UNI", name: "Uniswap", market: "CRYPTO" },
];


export function filterTickers(query: string, market: MarketRegion, maxResults: number = 10): TickerEntry[] {
  const q = query.toUpperCase().trim();
  if (!q) return [];
  return TICKER_DATABASE.filter(
    (t) => t.market === market && (t.ticker.startsWith(q) || t.name.toUpperCase().includes(q))
  ).slice(0, maxResults);
}

